### ISSUE TITLE
Mauritanie Flag

### ISSUE THREAD

**Issue by MrSimh** [apilayer/restcountries#248] opened 2021-09-13 15:46 UTC
The flag of mauritania is not correct since may 2020  https://fr.wikipedia.org/wiki/Drapeau_de_la_Mauritanie

**Comment by amatosg** [comment] 2021-09-13 17:20
same here: https://restcountries.com/v3/name/Mauritania

**Comment by ePascalC** [comment] 2021-09-29 12:48
Duplicate of #217

**Closed by ePascalC** 2021-09-29 12:48 UTC
