### ISSUE TITLE
521 Error when accessing API

### ISSUE THREAD

**Issue by tday** [apilayer/restcountries#196] opened 2020-08-18 14:15 UTC
Looks like the host is down. Any ETA on when the host will be brought back, if at all? Thanks!
![Screen Shot 2020-08-18 at 10 15 27 AM](https://user-images.githubusercontent.com/13629388/90524201-c6a14800-e13b-11ea-954d-7adc8578ec3a.png)

**Comment by amatosg** [comment] 2020-08-18 14:21
I have a similar project to this. You can try it on [here](https://restcountries.com/v2/alpha/codes=pe) (note that mine is _.com_ and not _.eu_)

**Comment by renato-bohler** [comment] 2020-08-18 14:24
Duplicate of #195

**Comment by MonilBhavsar** [comment] 2020-08-18 14:27
https://gitlab.com/amatos/rest-countries is an active alternative of this repo

**Comment by tday** [comment] 2020-08-18 14:42
Closing for the other issue that was opened almost simulataneously!

**Closed** 2020-08-18 14:42 UTC
